const SUBTITLE = {
  CODESQUAD_IN_MEDIA: "언론 보도 및 매체",
  CULTURE: "코드스쿼드의 가치가 녹아있는",
  FEATURE: "코드스쿼드는",
  MASTER: "코드스쿼드의 교육 가치를 실현하는",
  GRADUATE_INTERVIEW: "코드스쿼드의 교육을 경험한",
  MASTERS_COURSE: "마스터즈 코스의",
  PLACE: "코드스쿼드의 교육 철학이 담긴",
  MASTERS_COURSE_SCHEDULE: "대기자 신청부터 수료까지 한 눈에 확인하는",
  FAQ: "교육 과정에 대해",
  MASTERS_COURSE_2021: "마스터즈 코스를 경험한",
  TEAM_INTERIVIEW: "코드스쿼드 팀원들이 이야기하는",
  CODESQUAD_TEAM_CULTURE: "핵심 가치가 묻어난",
  WELFARE: "코드스쿼드 복지",
  CODE_TOGETHER: "코드투게더는",
  CODE_TOGETHER_COURSE: "코드투게더의",
  JAVASCRIPT: "자바스크립트 과정을 경험한",
  JAVASCRIPT_COURSE: "자바스크립트 과정의",
  PRE_COURSE: "프리 코스의",
  PRE_COURSE_TIME_TABLE: "우리는 과정중에",
  WE: "우리는",
};

const TITLE = {
  EDUCATION_TARGET: "교육 과정 대상자",
  CODESQUAD_IN_MEDIA: "미디어에서 본 코드스쿼드",
  CULTURE: "교육 및 학습 문화",
  FEATURE: "무엇이 다른가요?",
  MASTER: "분야별 전문 마스터",
  GRADUATE_INTERVIEW: "졸업생 후기",
  EDUCATION_FEATURES: "교육 특징",
  MASTERS_DETAIL_CURRICULUM: "각 클래스 별 상세 커리큘럼",
  JAVASCRIPT_DETAIL_CURRICULUM: "각 파트 별 상세 커리큘럼",
  PRE_COURSE_DETAIL_CURRICULUM: "각 클래스별 상세 커리큘럼",
  PRE_COURSE_TIME_TABLE: "어떻게 학습할까요?",
  PLACE: "오프라인 교육장",
  SCHEDULE: "곧 시작하는 과정",
  MASTERS_COURSE_SCHEDULE: "마스터즈 코스 스케쥴",
  FREQUENTLY_ASKED_QUESTIONS: "자주 묻는 질문",
  REFUND_POLICY: `코드스쿼드\n환불규정`,
  REFUND_REASON: "수강료 반환 원인",
  REFUND_STANDARD: "수강료 반환 기준",
  FAQ: "코드스쿼드에\n궁금한 점이 있나요?",
  APPLY: "지금 코드스쿼드에\n지원해 보세요!",
  WE: "우리는",
  WELCOME: "자유롭게 탐험하며\n함께 성장하는 동료를 만나세요",
  WELCOME_MOBILE: "자유롭게 탐험하며\n함께 성장하는\n동료를 만나세요",
  TEAM_INTERIVIEW: "우리가 일하는 방식",
  TEAM_CULTURE:
    "우리는 교육자와 학생\n 그리고 동료들과의 상호작용을 통해\n고품질 교육을 경험하는\n 배움터를 만듭니다",
  MOBILE_TEAM_CULTURE:
    "교육자와 학생 그리고 동료들과의 상호작용을 통해\n고품질 교육을 경험하는 배움터를 만듭니다",
  CODESQUAD_TEAM_CULTURE: "코드스쿼드 팀 문화",
  CODESQUAD_RECRUIT_NEWS: "코드스쿼드 채용 소식 확인하기",
  MOBILE_CODESQUAD_RECRUIT_NEWS: "코드스쿼드\n 채용 소식 확인하기",
  WELFARE: "우리는 어떤 지원을 받을까요?",
  COURSE: "교육 과정",
  HOW_STUDY: "어떻게 학습하나요?",
  STUDENT_INTERVIEW: "수강생 후기",
  SCHEDULED_COURSE: "지금 모집 중인 과정",
  VIEW_ENTIRE_COURSE: "전체 과정 보기",
  EDUCATION_PERIOD: "교육기간",
  COST: "수강료",
  CORETIME: "코어타임",
  MORE: "더보기",
  NOT_FOUND: "404",
  VIEW_COURSES: "코드스쿼드 과정 바로 보기",
  CODE_TOGETHER_COURSE: "코드투게더 과정",
  VIEW_DETAIL: "자세히 보기",
  FOLD: "접기",
};

const DESCRIPTION = {
  MASTER:
    "실무 경험이 풍부하고 소프트웨어 교육을 잘 이해하는 마스터들이 여러분의 성장을 위해 멘토링을 지원합니다.",
  PLACE:
    "도로명주소: 서울특별시 강남구 강남대로62길 23 4층 | 지번: 서울특별시 강남구 역삼동 836-24 4층",
  REFUND: `보다 자세한 사항은 관리자 메일 yoda@codesquad.kr 주소로 문의바랍니다.​\n코스 진행 이후 환불시 카드결제 수수료나 계좌이체 수수료에 대한 환불 수수료를 제외하고 환불해드립니다`,
  FRONT_CURRICULUM_LINK: "📣 마스터즈 코스 - 웹 프론트엔드",
  BACK_CURRICULUM_LINK: "📣 마스터즈 코스 - 웹 백엔드",
  IOS_CURRICULUM_LINK: "📣 마스터즈 코스 - 모바일 iOS",
  MOBILE_CURRICULUM_LINK: "모바일 Android",
  OR: " 또는 ",
  SUITABLE_READY_CLASS: "를 준비하는 분들에게 적합한 클래스입니다.",
};

const LINK = {
  BLOG: "블로그",
  CODE_TOGETHER: "코드투게더",
  CONFIRM_RECRUIT: "채용 소식 확인하기",
  FACEBOOK: "페이스북",
  FAQ: "자주 묻는 질문",
  MASTERS: "마스터즈",
  MASTERS_MAX: "마스터즈•max",
  PRE_COURSE: "프리코스",
  RECRUIT: "채용소식",
  REFUND_POLICY: "환불규정",
  SUBSCRIPTION: "소식받아보기",
  RECEIVE_SUBSCRIPTION: "코드스쿼드 소식 받아보기",
  TEAM_CULTURE: "팀 문화",
  YOUTUBE: "유튜브",
  KAKAOTALK_CHANNEL: "카카오톡 채널",
};

const LINK_DESCRIPTION = {
  CODE_TOGETHER: "온라인으로 함께 배우는 단기 과정",
  CONFIRM_RECRUIT: "코드스쿼드의 교육 가치에 공감한다면",
  MASTERS: "분야별 최고의 개발자가 되기 위한 풀타임 과정",
  PRE_COURSE: "프로그래밍 기초를 다지며 마스터즈를 준비할 수 있는 과정",
  RECEIVE_SUBSCRIPTION: "원하는 코스의 오픈 소식을 가장 먼저 알고 싶다면?",
};

const MESSAGE = {
  COPYRIGHT: "@2022 CodeSquad",
  COMPANY_ADDRESS: "주소: 강남구 역삼동 836-24 역삼빌딩 4층",
  ADDRESS: "강남구 역삼동 836-24 역삼빌딩 4층",
  COMPANY_CEO_NAME: "대표자: 김정",
  COMPANY_EMAIL: "대표 이메일: ",
  COMPANY_EMAIL_ADDRESS: "yoda@codesquad.kr",
  COMPANY_NAME: "코드스쿼드",
  COMPANY_REGISTRATION_NUMBER: "사업자등록번호: 676-88-00504",
  COMPANY_MAIL_ORDER_SALES_REGISTRATION_NUMBER: "통신판매신고: 제 2017-서울강남-04281호",
  COMPANY_TEL_NUMBER: "전화: 070-4117-1005",
  TEL_NUMBER: "070-4117-1005",
  CURRICULUM: "교육 과정",
  SOCIAL_MEDIA: "미디어",
};

const CATEGORTY_TPL: { [key: string]: string } = {
  masters: "마스터즈 코스",
  javascript: "코드투게더 JS 과정",
  "pre-course": "프리코스",
  etc: "기타",
};

export { DESCRIPTION, LINK_DESCRIPTION, LINK, MESSAGE, SUBTITLE, TITLE, CATEGORTY_TPL };
